"""
AI Orchestrator Bridge v0.3 -- OpenAI planner module (Phase B).

Calls the OpenAI Chat Completions API using urllib.request (stdlib only).
No openai SDK required. No pip install needed.

Public API:
    improve_task(report_text, local_draft, local_decision, config) -> str
    log_api_call(log_dir, model, tokens_used, decision, success)

Exceptions:
    MissingApiKeyError  -- OPENAI_API_KEY not set in environment
    ApiCallError        -- HTTP / network / parse error from OpenAI

Security rules (enforced here, not just in docs):
  - API key is read from os.environ ONLY.
  - API key is NEVER written to logs, state files, or returned values.
  - Full request/response bodies are NEVER written to logs.
  - Only metadata (model, token counts, decision, success flag) is logged.
"""

import json
import os
import urllib.error
import urllib.request
from datetime import datetime
from pathlib import Path


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class PlannerError(Exception):
    """Base class for planner errors."""

class MissingApiKeyError(PlannerError):
    """OPENAI_API_KEY environment variable is not set."""

class ApiCallError(PlannerError):
    """HTTP, network, or response-parse error from OpenAI."""


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """\
You are a task planner for an AI coding assistant named Claude Code.
Your only job is to generate a safe, focused, and detailed NEXT_TASK.md document.

Output rules:
- Output ONLY the improved task document. No preamble, no explanation, no apology.
- Start the document with a markdown heading: # Next Task
- Include sections: Goal, Context, Preflight checks, Allowed actions,
  Forbidden actions, Verification gates, Final report requirements.
- Do NOT include any of the following unless the session report explicitly requires them:
  git push, git push --force, git tag, gh release, gh pr create,
  git reset --hard, git clean, git stash pop, npm install, yarn add,
  pip install, rm -rf, --execute, schema change, migration, force-push,
  delete the branch, drop the stash.
- Do NOT invent scope that is not in the session report.
- Do NOT reference external URLs or services not mentioned in the report.
- If the report mentions TradingView or drawing tools, include this EXACT rule
  in the Forbidden actions section:
  "drawing-tool changes must apply by default to the unified sheet that includes
  two panes/modes: Standard and Transform 2x2."
- Write the task so a human can review it safely before giving it to Claude Code.
"""


def _build_user_message(
    report_text: str,
    local_draft: str,
    local_decision: dict,
) -> str:
    decision_label = local_decision.get("decision", "unknown")
    risk_label     = local_decision.get("risk_level", "unknown")
    reason         = local_decision.get("reason", "(none)")
    allowed        = local_decision.get("allowed_actions", [])
    forbidden      = local_decision.get("forbidden_actions", [])

    allowed_str   = ", ".join(allowed[:8])   if allowed   else "(none identified)"
    forbidden_str = ", ".join(forbidden[:8]) if forbidden else "(none identified)"

    # Truncate large inputs to stay within token budget
    report_snippet = report_text[:5000] + ("\n...[report truncated]" if len(report_text) > 5000 else "")
    draft_snippet  = local_draft[:2500]  + ("\n...[draft truncated]"  if len(local_draft)  > 2500 else "")

    return (
        "## Session Report\n\n"
        f"{report_snippet}\n\n"
        "## Local Risk Context (from offline classifier)\n\n"
        f"Decision:                 {decision_label}\n"
        f"Risk level:               {risk_label}\n"
        f"Reason:                   {reason}\n"
        f"Allowed actions:          {allowed_str}\n"
        f"Actions needing approval: {forbidden_str}\n\n"
        "## Draft Task (generated by local template planner)\n\n"
        f"{draft_snippet}\n\n"
        "Please generate an improved NEXT_TASK.md that is more detailed and actionable, "
        "while respecting the risk context above. "
        "If the risk level is 'medium' or 'high', reflect that in the task's "
        "Forbidden actions and Verification gates sections."
    )


# ---------------------------------------------------------------------------
# HTTP call (urllib only)
# ---------------------------------------------------------------------------

_OPENAI_ENDPOINT = "https://api.openai.com/v1/chat/completions"


def call_openai(
    api_key: str,
    model: str,
    messages: "list[dict]",
    max_tokens: int = 2048,
    timeout: int = 60,
) -> "tuple[str, int]":
    """
    Call OpenAI Chat Completions. Returns (content_str, total_tokens).
    Raises ApiCallError on any failure.
    Never logs or exposes api_key.
    """
    payload = json.dumps({
        "model":       model,
        "messages":    messages,
        "max_tokens":  max_tokens,
        "temperature": 0,
    }).encode("utf-8")

    req = urllib.request.Request(
        _OPENAI_ENDPOINT,
        data=payload,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type":  "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        status = exc.code
        try:
            err_body = json.loads(exc.read().decode("utf-8", errors="replace"))
            err_msg  = err_body.get("error", {}).get("message", str(exc))
        except Exception:
            err_msg = str(exc)
        if status == 401:
            raise ApiCallError("OpenAI 401 Unauthorized: check OPENAI_API_KEY") from exc
        if status == 429:
            raise ApiCallError("OpenAI 429 Rate limit exceeded; retry later") from exc
        raise ApiCallError(f"OpenAI HTTP {status}: {err_msg}") from exc
    except urllib.error.URLError as exc:
        raise ApiCallError(f"OpenAI network error: {exc.reason}") from exc
    except TimeoutError as exc:
        raise ApiCallError(f"OpenAI request timed out after {timeout}s") from exc
    except json.JSONDecodeError as exc:
        raise ApiCallError(f"OpenAI response JSON parse error: {exc}") from exc

    try:
        content      = body["choices"][0]["message"]["content"].strip()
        total_tokens = body.get("usage", {}).get("total_tokens", 0)
        return content, total_tokens
    except (KeyError, IndexError) as exc:
        raise ApiCallError(f"Unexpected OpenAI response structure: {exc}") from exc


# ---------------------------------------------------------------------------
# Metadata-only call log (no key, no content)
# ---------------------------------------------------------------------------

def log_api_call(
    log_dir: Path,
    model: str,
    tokens_used: int,
    decision: str,
    success: bool,
    error_type: str = "",
) -> None:
    """Append a one-line metadata entry to logs/openai-calls.log."""
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / "openai-calls.log"
    ts   = datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
    ok   = "OK" if success else f"FAIL:{error_type}"
    line = f"[{ts}] model={model} tokens={tokens_used} decision={decision} status={ok}\n"
    try:
        with open(log_path, "a", encoding="utf-8") as fh:
            fh.write(line)
    except OSError:
        pass  # log failure is non-fatal


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def improve_task(
    report_text: str,
    local_draft: str,
    local_decision: dict,
    config: dict,
) -> str:
    """
    Generate an improved NEXT_TASK.md using the OpenAI API.

    Reads OPENAI_API_KEY from environment only.
    Raises MissingApiKeyError if key absent.
    Raises ApiCallError on HTTP or network failure.
    Returns the improved task text as a string.
    """
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not api_key:
        raise MissingApiKeyError(
            "OPENAI_API_KEY environment variable is not set. "
            "Set it in your shell:  $env:OPENAI_API_KEY='<your-key>'  "
            "Never put the key in config files."
        )

    planner_cfg = config.get("planner", {}).get("openai", {})
    model      = planner_cfg.get("model",             "gpt-4o")
    max_tokens = planner_cfg.get("max_output_tokens", 2048)
    timeout    = planner_cfg.get("timeout_seconds",   60)

    messages = [
        {"role": "system", "content": _SYSTEM_PROMPT},
        {"role": "user",   "content": _build_user_message(report_text, local_draft, local_decision)},
    ]

    content, _tokens = call_openai(api_key, model, messages, max_tokens=max_tokens, timeout=timeout)
    return content
